<a href="https://colab.research.google.com/github/Auta01/Hugging-face/blob/main/Dataset%20library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
from datasets import load_dataset

ds = load_dataset("stanfordnlp/imdb")

In [35]:
type(ds)

datasets.dataset_dict.DatasetDict

In [36]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [37]:
ds['train']

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

In [38]:
import pandas as pd
ds['train'].to_pandas()

                                                    text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  A hit at the time but now better categorised a...      1
24996  I love this movie like no other. Another time ...      1
24997  This film and it's sequel Barry Mckenzie holds...      1
24998  'The Adventures Of Barry McKenzie' started lif...      1
24999  The story centers around Barry McKenzie who mu...      1

[25000 rows x 2 columns]

In [39]:
my_dataset_df = ds['train'].to_pandas()

In [40]:
my_dataset_df['text']

0        I rented I AM CURIOUS-YELLOW from my video sto...
1        "I Am Curious: Yellow" is a risible and preten...
2        If only to avoid making this type of film in t...
3        This film was probably inspired by Godard's Ma...
4        Oh, brother...after hearing about this ridicul...
                               ...
24995    A hit at the time but now better categorised a...
24996    I love this movie like no other. Another time ...
24997    This film and it's sequel Barry Mckenzie holds...
24998    'The Adventures Of Barry McKenzie' started lif...
24999    The story centers around Barry McKenzie who mu...
Name: text, Length: 25000, dtype: object

In [41]:
len(my_dataset_df['text'])

25000

In [42]:
from transformers import pipeline
pipe = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [43]:
pipe('This day is great')

[{'label': 'POSITIVE', 'score': 0.9998873472213745}]

In [44]:
pipe =('This day is terrible and i am so sad')

In [46]:
def score(review_text):
  return pipe(review_text[:500])[0]['label']

In [47]:
my_dataset_df['model_prediction'] = my_dataset_df['text'].apply(score)

In [47]:
my_dataset_df

In [48]:
from transformers import pipeline

pipe = pipeline("text-classification", model="ProsusAI/finbert")

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [51]:
sentence = 'The company reported  a strong increase in quartely revenue, exceding market expectations.'
pipe(sentence)

[{'label': 'positive', 'score': 0.9546364545822144}]

In [52]:
sentence = 'shares fell after the firm reported lower-than-expected earnings'
pipe(sentence)

[{'label': 'negative', 'score': 0.9718543887138367}]

In [53]:
sentence= ['strong consumerr demand drove record sales across all regions',
           'supply chain distribution severly affected producttion output ']
pipe(sentence)

[{'label': 'positive', 'score': 0.9464541673660278},
 {'label': 'negative', 'score': 0.9465852379798889}]

Named Entity Recognition

In [54]:
sentence ='Apple announced record earning in the united states on monday'

In [55]:
ner =pipeline('ner')
ner(sentence)

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

BertForTokenClassification LOAD REPORT from: dbmdz/bert-large-cased-finetuned-conll03-english
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

[{'entity': 'I-ORG',
  'score': np.float32(0.9989932),
  'index': 1,
  'word': 'Apple',
  'start': 0,
  'end': 5}]

Question&Answering

In [56]:
qa_bot = pipeline('question-answering')

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [57]:
context = ''' Financial sentiment analysis is a challenge task due to the specialized
language and lack of labeled data in that domain. General-purpose models are not effective enough because of the specialized language used in a financial context. we hypothesize that pre-trained language models can help with this problem because they require fewer labeled example and they can be further trained on domain-specific corpora. we introduce finbert a language model based on bert, to tackle nlp tasks in the financial domain our resluts show improvement in every measured metric on current state-of-the-art results for two financial sentiment analysis datasets we find that even with a smaller training set and fine-tuning only a part of the model, finbert outperforms state-of-the-art machine learnig methods.
'''

In [62]:
question = 'what is finacial sentiment analysis?'

In [61]:
qa_bot(question=question, context=context)

{'score': 0.5531672239303589,
 'start': 33,
 'end': 49,
 'answer': 'a challenge task'}